"use client";
import { useEffect, useState } from "react";
import {
  HEALTH_BANDS,
  WORK_DEPARTMENTS,
  WORK_PRIORITIES,
  creators,
  reports,
  type DailyReport,
} from "@creatoros/domain";
import { Check, ListChecks } from "lucide-react";
import { z } from "zod";
import { DemoStrip, PageHeader } from "@/components/page-header";
import { LiveEmpty } from "@/components/live-empty";
import { useDemoMode } from "@/components/mode-provider";
import { StatusBadge } from "@/components/status-badge";
export default function ReportsPage() {
  const demo = useDemoMode();
  const [reportRecords, setReportRecords] = useState<Array<DailyReport & { creatorName: string }>>(
    demo
      ? reports.map((report) => ({
          ...report,
          creatorName:
            creators.find((item) => item.id === report.creatorId)?.stageName ?? "Creator",
        }))
      : [],
  );
  const [created, setCreated] = useState<string[]>([]);
  const [message, setMessage] = useState("");
  useEffect(() => {
    if (demo) return;
    void fetch("/api/reports/daily")
      .then((response) => response.json())
      .then((body: unknown) => {
        const envelope = z.object({ data: z.array(z.unknown()) }).safeParse(body);
        if (!envelope.success) return;
        // Parsed one report at a time rather than as a single z.array(...): a
        // report the client schema can't yet represent -- an added enum value,
        // a shape change -- used to fail the whole array's parse and blank
        // the entire org's report inbox for every creator, not just the one
        // report that didn't fit. One bad report is now dropped and logged,
        // not a reason to hide everyone else's.
        const parsedReports = envelope.data.data.flatMap((raw) => {
          const result = liveReportSchema.safeParse(raw);
          if (!result.success) {
            console.warn("Skipping a daily report the client could not parse", result.error);
            return [];
          }
          return [result.data];
        });
        setReportRecords(
          parsedReports.map((report) => ({
            id: report.id,
            creatorId: report.creator_id,
            creatorName: report.creators?.stage_name ?? "Creator",
            reportDate: report.report_date,
            status: "READY" as const,
            healthBand: report.health_status ?? "WATCH",
            summary: report.summary,
            primaryBottleneck: report.primary_bottleneck ?? "No primary bottleneck",
            priority: report.priority ?? "NORMAL",
            metrics: report.metrics_json,
            comparisons: {},
            anomalies: report.anomalies_json,
            recommendations: report.recommendations_json.map((item, index) => ({
              id: item.id ?? `${report.id}-${index}`,
              department: item.department,
              action: item.action,
              evidence: "CreatorOS report",
              priority: item.priority,
              suggestedOwner: "Assigned team",
              dueInDays: 3,
              confidence: "MEASURED" as const,
              sourceRule: report.data_quality_json?.ruleId ?? "UNKNOWN",
            })),
            ruleId: report.data_quality_json?.ruleId ?? "UNKNOWN",
            provider: "RULES" as const,
          })),
        );
      });
  }, [demo]);

  async function createTasks(reportId: string) {
    if (demo) {
      setCreated((current) => (current.includes(reportId) ? current : [...current, reportId]));
      return;
    }
    const response = await fetch(`/api/reports/${reportId}/tasks`, { method: "POST" });
    const body = (await response.json()) as { error?: string };
    if (!response.ok) {
      setMessage(body.error ?? "Task creation failed");
      return;
    }
    setCreated((current) => (current.includes(reportId) ? current : [...current, reportId]));
  }
  return (
    <main className="page">
      <DemoStrip />
      <PageHeader
        eyebrow="Daily intelligence"
        title="Report inbox"
        subtitle="Exception-led operating reports generated by explainable rules before optional AI enrichment."
      />
      {message ? (
        <div className="demo-strip" role="status">
          {message}
        </div>
      ) : null}
      {reportRecords.length === 0 ? (
        <LiveEmpty
          title="No reports generated yet"
          hint="Daily reports appear here once a creator has a frozen baseline and measured metrics to compare against it."
        />
      ) : (
      <div className="grid">
        {reportRecords.map((report) => {
          const made = created.includes(report.id);
          return (
            <article className="card card-pad" key={report.id}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: 18,
                  alignItems: "flex-start",
                }}
              >
                <div>
                  <div className="eyebrow">
                    {report.reportDate} · {report.ruleId}
                  </div>
                  <h2 style={{ fontFamily: "Georgia,serif", fontSize: 23, marginTop: 4 }}>
                    {report.creatorName}
                  </h2>
                  <StatusBadge value={report.healthBand} />
                </div>
                <div className="actions">
                  <button
                    className="button"
                    onClick={() => void createTasks(report.id)}
                    disabled={made}
                  >
                    {made ? (
                      <>
                        <Check size={14} /> Tasks created
                      </>
                    ) : (
                      <>
                        <ListChecks size={14} /> Create recommended tasks
                      </>
                    )}
                  </button>
                  <a className="button primary" href={`/creators/${report.creatorId}`}>
                    Open creator
                  </a>
                </div>
              </div>
              <div className="grid detail-grid" style={{ marginTop: 18 }}>
                <div>
                  <span className="eyebrow">PRIMARY BOTTLENECK</span>
                  <h3 style={{ marginTop: 6 }}>{report.primaryBottleneck}</h3>
                  <p className="subtitle">{report.summary}</p>
                </div>
                <div>
                  <span className="eyebrow">SIGNALS</span>
                  {report.anomalies.length ? (
                    report.anomalies.map((item) => (
                      <p className="subtitle" style={{ marginTop: 6 }} key={item.message}>
                        • {item.message}
                      </p>
                    ))
                  ) : (
                    <p className="subtitle" style={{ marginTop: 6 }}>
                      No material anomaly detected.
                    </p>
                  )}
                </div>
                <div>
                  <span className="eyebrow">NEXT ACTIONS</span>
                  {report.recommendations.slice(0, 3).map((rec) => (
                    <p className="subtitle" style={{ marginTop: 6 }} key={rec.id}>
                      • {rec.department}: {rec.action}
                    </p>
                  ))}
                </div>
              </div>
            </article>
          );
        })}
      </div>
      )}
    </main>
  );
}

const liveReportSchema = z.object({
  id: z.string().uuid(),
  creator_id: z.string().uuid(),
  creators: z.object({ stage_name: z.string() }).nullable().optional(),
  report_date: z.string(),
  // Every band in the canonical list, including UNKNOWN -- the value
  // healthBand() (packages/domain/src/health-score.ts) returns for a
  // creator with no measured score yet. Missing it here meant a single
  // freshly onboarded creator's report -- the state every new creator
  // starts in -- failed this report's parse and, before parsing moved to
  // one report at a time, blanked the whole org's inbox for it.
  health_status: z.enum(HEALTH_BANDS).nullable(),
  summary: z.string(),
  primary_bottleneck: z.string().nullable(),
  priority: z.enum(["CRITICAL", "HIGH", "NORMAL"]).nullable(),
  anomalies_json: z.array(
    z.object({ severity: z.enum(["CRITICAL", "WARNING", "OPPORTUNITY"]), message: z.string() }),
  ),
  recommendations_json: z.array(
    z.object({
      id: z.string().optional(),
      department: z.enum(WORK_DEPARTMENTS),
      priority: z.enum(WORK_PRIORITIES),
      action: z.string(),
    }),
  ),
  // The real per-report metrics and the rule that produced the report
  // (apps/web/src/lib/daily-report.ts writes both into the row -- metrics
  // under metrics_json, the rule id under data_quality_json.ruleId). The API
  // route already selects both; only this page was ignoring them in favor of
  // an all-zero metrics object and the literal string "DATABASE".
  metrics_json: z.object({
    date: z.string(),
    reach: z.coerce.number(),
    profileVisits: z.coerce.number(),
    outboundClicks: z.coerce.number(),
    newSubscribers: z.coerce.number(),
    firstBuyers: z.coerce.number(),
    revenue: z.coerce.number(),
  }),
  data_quality_json: z.object({ ruleId: z.string().optional() }).nullable().optional(),
});
