"use client";
import { useEffect, useState } from "react";
import { creators, reports, type DailyReport } from "@creatoros/domain";
import { Check, ListChecks } from "lucide-react";
import { z } from "zod";
import { DemoStrip, PageHeader } from "@/components/page-header";
import { useDemoMode } from "@/components/mode-provider";
import { StatusBadge } from "@/components/status-badge";
export default function ReportsPage() {
  const demo = useDemoMode();
  const [reportRecords, setReportRecords] = useState<Array<DailyReport & { creatorName: string }>>(
    demo
      ? reports.map((report) => ({
          ...report,
          creatorName:
            creators.find((item) => item.id === report.creatorId)?.stageName ?? "Creator",
        }))
      : [],
  );
  const [created, setCreated] = useState<string[]>([]);
  const [message, setMessage] = useState("");
  useEffect(() => {
    if (demo) return;
    void fetch("/api/reports/daily")
      .then((response) => response.json())
      .then((body: unknown) => {
        const parsed = liveReportsResponse.safeParse(body);
        if (!parsed.success) return;
        setReportRecords(
          parsed.data.data.map((report) => ({
            id: report.id,
            creatorId: report.creator_id,
            creatorName: report.creators?.stage_name ?? "Creator",
            reportDate: report.report_date,
            status: "READY" as const,
            healthBand: report.health_status ?? "WATCH",
            summary: report.summary,
            primaryBottleneck: report.primary_bottleneck ?? "No primary bottleneck",
            priority: report.priority ?? "NORMAL",
            metrics: {
              date: report.report_date,
              reach: 0,
              profileVisits: 0,
              outboundClicks: 0,
              newSubscribers: 0,
              firstBuyers: 0,
              revenue: 0,
            },
            comparisons: {},
            anomalies: report.anomalies_json,
            recommendations: report.recommendations_json.map((item, index) => ({
              id: item.id ?? `${report.id}-${index}`,
              department: item.department,
              action: item.action,
              evidence: "CreatorOS report",
              priority: item.priority,
              suggestedOwner: "Assigned team",
              dueInDays: 3,
              confidence: "MEASURED" as const,
              sourceRule: "DATABASE",
            })),
            ruleId: "DATABASE",
            provider: "RULES" as const,
          })),
        );
      });
  }, [demo]);

  async function createTasks(reportId: string) {
    if (demo) {
      setCreated((current) => (current.includes(reportId) ? current : [...current, reportId]));
      return;
    }
    const response = await fetch(`/api/reports/${reportId}/tasks`, { method: "POST" });
    const body = (await response.json()) as { error?: string };
    if (!response.ok) {
      setMessage(body.error ?? "Task creation failed");
      return;
    }
    setCreated((current) => (current.includes(reportId) ? current : [...current, reportId]));
  }
  return (
    <main className="page">
      <DemoStrip />
      <PageHeader
        eyebrow="Daily intelligence"
        title="Report inbox"
        subtitle="Exception-led operating reports generated by explainable rules before optional AI enrichment."
      />
      {message ? (
        <div className="demo-strip" role="status">
          {message}
        </div>
      ) : null}
      <div className="grid">
        {reportRecords.map((report) => {
          const made = created.includes(report.id);
          return (
            <article className="card card-pad" key={report.id}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: 18,
                  alignItems: "flex-start",
                }}
              >
                <div>
                  <div className="eyebrow">
                    {report.reportDate} · {report.ruleId}
                  </div>
                  <h2 style={{ fontFamily: "Georgia,serif", fontSize: 23, marginTop: 4 }}>
                    {report.creatorName}
                  </h2>
                  <StatusBadge value={report.healthBand} />
                </div>
                <div className="actions">
                  <button
                    className="button"
                    onClick={() => void createTasks(report.id)}
                    disabled={made}
                  >
                    {made ? (
                      <>
                        <Check size={14} /> Tasks created
                      </>
                    ) : (
                      <>
                        <ListChecks size={14} /> Create recommended tasks
                      </>
                    )}
                  </button>
                  <a className="button primary" href={`/creators/${report.creatorId}`}>
                    Open creator
                  </a>
                </div>
              </div>
              <div className="grid detail-grid" style={{ marginTop: 18 }}>
                <div>
                  <span className="eyebrow">PRIMARY BOTTLENECK</span>
                  <h3 style={{ marginTop: 6 }}>{report.primaryBottleneck}</h3>
                  <p className="subtitle">{report.summary}</p>
                </div>
                <div>
                  <span className="eyebrow">SIGNALS</span>
                  {report.anomalies.length ? (
                    report.anomalies.map((item) => (
                      <p className="subtitle" style={{ marginTop: 6 }} key={item.message}>
                        • {item.message}
                      </p>
                    ))
                  ) : (
                    <p className="subtitle" style={{ marginTop: 6 }}>
                      No material anomaly detected.
                    </p>
                  )}
                </div>
                <div>
                  <span className="eyebrow">NEXT ACTIONS</span>
                  {report.recommendations.slice(0, 3).map((rec) => (
                    <p className="subtitle" style={{ marginTop: 6 }} key={rec.id}>
                      • {rec.department}: {rec.action}
                    </p>
                  ))}
                </div>
              </div>
            </article>
          );
        })}
      </div>
    </main>
  );
}

const liveReportsResponse = z.object({
  data: z.array(
    z.object({
      id: z.string().uuid(),
      creator_id: z.string().uuid(),
      creators: z.object({ stage_name: z.string() }).nullable().optional(),
      report_date: z.string(),
      health_status: z.enum(["WATCH", "GREEN", "AT_RISK", "CRITICAL"]).nullable(),
      summary: z.string(),
      primary_bottleneck: z.string().nullable(),
      priority: z.enum(["CRITICAL", "HIGH", "NORMAL"]).nullable(),
      anomalies_json: z.array(
        z.object({ severity: z.enum(["CRITICAL", "WARNING", "OPPORTUNITY"]), message: z.string() }),
      ),
      recommendations_json: z.array(
        z.object({
          id: z.string().optional(),
          department: z.enum([
            "Growth",
            "Creative",
            "Creator Success",
            "Revenue",
            "Operations",
            "Security",
            "Compliance",
          ]),
          priority: z.enum(["CRITICAL", "HIGH", "MEDIUM", "LOW"]),
          action: z.string(),
        }),
      ),
    }),
  ),
});
