"use client";
import { useState } from "react";
import { creators, reports } from "@creatoros/domain";
import { Check, ListChecks } from "lucide-react";
import { DemoStrip, PageHeader } from "@/components/page-header";
import { StatusBadge } from "@/components/status-badge";
export default function ReportsPage() {
  const [created, setCreated] = useState<string[]>([]);
  return (
    <main className="page">
      <DemoStrip />
      <PageHeader
        eyebrow="Daily intelligence"
        title="Report inbox"
        subtitle="Exception-led operating reports generated by explainable rules before optional AI enrichment."
      />
      <div className="grid">
        {reports.map((report) => {
          const creator = creators.find((item) => item.id === report.creatorId);
          const made = created.includes(report.id);
          return (
            <article className="card card-pad" key={report.id}>
              <div
                style={{
                  display: "flex",
                  justifyContent: "space-between",
                  gap: 18,
                  alignItems: "flex-start",
                }}
              >
                <div>
                  <div className="eyebrow">
                    {report.reportDate} · {report.ruleId}
                  </div>
                  <h2 style={{ fontFamily: "Georgia,serif", fontSize: 23, marginTop: 4 }}>
                    {creator?.stageName}
                  </h2>
                  <StatusBadge value={report.healthBand} />
                </div>
                <div className="actions">
                  <button
                    className="button"
                    onClick={() =>
                      setCreated((current) =>
                        current.includes(report.id) ? current : [...current, report.id],
                      )
                    }
                    disabled={made}
                  >
                    {made ? (
                      <>
                        <Check size={14} /> Tasks created
                      </>
                    ) : (
                      <>
                        <ListChecks size={14} /> Create recommended tasks
                      </>
                    )}
                  </button>
                  <a className="button primary" href={`/creators/${report.creatorId}`}>
                    Open creator
                  </a>
                </div>
              </div>
              <div className="grid detail-grid" style={{ marginTop: 18 }}>
                <div>
                  <span className="eyebrow">PRIMARY BOTTLENECK</span>
                  <h3 style={{ marginTop: 6 }}>{report.primaryBottleneck}</h3>
                  <p className="subtitle">{report.summary}</p>
                </div>
                <div>
                  <span className="eyebrow">SIGNALS</span>
                  {report.anomalies.length ? (
                    report.anomalies.map((item) => (
                      <p className="subtitle" style={{ marginTop: 6 }} key={item.message}>
                        • {item.message}
                      </p>
                    ))
                  ) : (
                    <p className="subtitle" style={{ marginTop: 6 }}>
                      No material anomaly detected.
                    </p>
                  )}
                </div>
                <div>
                  <span className="eyebrow">NEXT ACTIONS</span>
                  {report.recommendations.slice(0, 3).map((rec) => (
                    <p className="subtitle" style={{ marginTop: 6 }} key={rec.id}>
                      • {rec.department}: {rec.action}
                    </p>
                  ))}
                </div>
              </div>
            </article>
          );
        })}
      </div>
    </main>
  );
}
