begin;

create extension if not exists pgcrypto;
create sequence if not exists creator_number_seq start 1;
create sequence if not exists prospect_number_seq start 1;
create sequence if not exists onboarding_number_seq start 1;

create type public.organization_role as enum ('super_admin','growth','creator_success','fan_ops','editor','analyst','finance','contractor','viewer');
create type public.creator_status as enum ('ONBOARDING','ACTIVE','WATCH','PAUSED','OFFBOARDING','FORMER');
create type public.workflow_status as enum ('RUNNING','WAITING_EXTERNAL','SUCCEEDED','FAILED','BLOCKED','CANCELLED');
create type public.workflow_step_status as enum ('PENDING','READY','RUNNING','SUCCEEDED','FAILED','BLOCKED','SKIPPED','CANCELLED','WAITING_EXTERNAL');
create type public.integration_status as enum ('NOT_CONFIGURED','CONFIGURED','CONNECTING','CONNECTED','DEGRADED','ERROR','DISCONNECTED');
create type public.data_confidence as enum ('MEASURED','PARTIALLY_MEASURED','ESTIMATED','UNKNOWN');

create table public.organizations (
  id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique,
  settings_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.users (
  id uuid primary key references auth.users(id) on delete cascade, display_name text, email text not null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.organization_memberships (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), user_id uuid not null references public.users(id),
  role public.organization_role not null, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,user_id)
);
create table public.custom_roles (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null,
  permissions text[] not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(organization_id,name)
);
create table public.prospects (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), prospect_number text not null default ('PR-'||lpad(nextval('prospect_number_seq')::text,6,'0')),
  preferred_name text not null, stage_name text not null, email text, phone text, country text, region text, timezone text,
  instagram_url text, tiktok_url text, x_url text, youtube_url text, subscription_platform_url text, primary_social_platform text,
  niche text, secondary_niche text, follower_count_estimate bigint, engagement_quality text, current_management_status text, current_agency_name text,
  estimated_revenue_range text, public_funnel_notes text, opportunity_notes text, personalized_observation text, source text, referral_source text,
  assigned_owner uuid, fit_score integer check(fit_score between 0 and 100), fit_tier text, qualification_status text, pipeline_stage text not null default 'SOURCED',
  disqualifying_flags text[] not null default '{}', fit_components_json jsonb not null default '{}'::jsonb, last_contact_at timestamptz, next_followup_at timestamptz,
  lost_reason text, internal_notes text, created_by uuid, updated_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz,
  unique(organization_id,prospect_number)
);
create table public.prospect_activities (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), prospect_id uuid not null references public.prospects(id),
  activity_type text not null, body text, occurred_at timestamptz not null default now(), created_by uuid, created_at timestamptz not null default now()
);
create table public.creator_applications (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), preferred_name text not null, stage_name text not null,
  email text not null, phone text, country text, region text, timezone text, instagram_url text, tiktok_url text, x_url text, youtube_url text,
  subscription_platform_url text, primary_platform text, revenue_range text, management_status text, fan_ops_status text, editor_status text,
  weekly_content_capacity integer, consistency text, bottleneck text, requested_support text[], twelve_month_goal text, acquisition_source text, referral_name text,
  adult_confirmation boolean not null default false, consent boolean not null default false, review_status text not null default 'NEW',
  associated_prospect_id uuid references public.prospects(id), converted_creator_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.creators (
  id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_number text not null default ('CR-'||lpad(nextval('creator_number_seq')::text,6,'0')),
  preferred_name text not null, stage_name text not null, legal_entity_name text, email text not null, phone text, country text, region text, timezone text not null,
  start_date date not null, status public.creator_status not null default 'ONBOARDING', assigned_creator_success_user_id uuid, assigned_growth_user_id uuid,
  management_model text, commission_percentage numeric(5,2), commission_basis text, contract_status text not null, contract_start_date date, contract_end_date date,
  jurisdiction_review_status text not null, adult_confirmation_status text not null default 'NOT_STARTED', root_owner text not null default 'creator',
  recovery_owner text not null default 'creator', payout_control text not null default 'creator_controlled', mfa_status text, security_review_status text,
  primary_platform text, baseline_revenue_range text, current_health_status text, current_health_score integer check(current_health_score between 0 and 100),
  current_content_buffer_days integer, last_review_at timestamptz, next_review_at timestamptz, source_prospect_id uuid references public.prospects(id),
  source_application_id uuid references public.creator_applications(id), created_by uuid, updated_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), archived_at timestamptz,
  unique(organization_id,creator_number), unique(organization_id,email)
);
alter table public.creator_applications add constraint creator_applications_converted_creator_fk foreign key (converted_creator_id) references public.creators(id);

create table public.creator_brand_profiles (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null unique references public.creators(id), known_for text, positioning_statement text, primary_audience text, secondary_audience text, niche text, sub_niche text, personality_traits text[], archetype text, tone text, humor text, warmth text, assertiveness text, environments text[], framing text[], wardrobe_categories text[], lighting text[], editing_style text, sentence_style text, emoji_style text, slang text[], vocabulary text[], punctuation text, approved_flirtiness_range text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.creator_truth_items (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), item_type text not null check(item_type in ('approved','requires_creator_confirmation','prohibited')), category text not null, statement text not null, notes text, status text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.creator_boundaries (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), boundary_type text not null, description text not null, severity text not null, requires_creator_approval boolean not null default false, active boolean not null default true, source text, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.content_pillars (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), name text not null, description text, strategic_role text, active boolean not null default true, priority integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(creator_id,name));
create table public.content_franchises (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), name text not null, description text, hypothesis text, status text not null default 'CANDIDATE', first_test_at timestamptz, last_test_at timestamptz, executions integer not null default 0, rolling_median_performance numeric, performance_multiplier numeric, primary_metric text, fatigue_score numeric, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(creator_id,name));
create table public.creator_competitors (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), competitor_name text not null, platform text, profile_url text, competitor_type text not null check(competitor_type in ('DIRECT','ASPIRATIONAL','ADJACENT')), niche text, audience_notes text, positioning_notes text, funnel_notes text, recurring_formats text[], recurring_hooks text[], common_environments text[], posting_frequency_notes text, cta_patterns text[], public_link_path text, strategic_takeaways text, last_reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.creative_patterns (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), pattern_name text not null, description text, source_scope text, observed_competitor_count integer, applicable_niches text[], evidence_notes text, confidence public.data_confidence not null default 'UNKNOWN', status text, first_observed_at timestamptz, last_observed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.experiments (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), name text not null, experiment_type text, hypothesis text not null, control_description text, variant_description text, primary_metric text not null, secondary_metrics text[], started_at timestamptz, ended_at timestamptz, status text not null default 'DRAFT', sample_notes text, result text, confidence public.data_confidence not null default 'UNKNOWN', decision text, created_by uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.content_requests (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), title text not null, platform text, objective text, priority text, content_pillar_id uuid references public.content_pillars(id), franchise_id uuid references public.content_franchises(id), experiment_id uuid references public.experiments(id), concept text, hook text, shot_list text[], duration_guidance text, reference_url text, notes text, requested_by uuid, assigned_creator boolean not null default true, due_at timestamptz, status text not null default 'REQUESTED', creator_acknowledged_at timestamptz, submitted_at timestamptz, approved_at timestamptz, published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.content_assets (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), external_storage_id text, asset_type text, platform text, safe_classification text not null, title text, file_reference text, capture_date date, received_date date, approval_status text, inventory_category text, used_count integer not null default 0, last_used_at timestamptz, tags text[], notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.content_inventory_snapshots (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), social_buffer_days integer, wall_buffer_days integer, premium_inventory_count integer, story_buffer_days integer, snapshot_date date not null, created_at timestamptz not null default now(), unique(creator_id,snapshot_date));
create table public.social_accounts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), provider text not null, handle text, profile_url text, external_account_id text, connection_status public.integration_status not null default 'NOT_CONFIGURED', connection_method text, last_sync_at timestamptz, sync_health text, metadata_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.social_posts (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), social_account_id uuid references public.social_accounts(id), external_post_id text, platform text not null, published_at timestamptz not null, format text, content_pillar text, franchise_id uuid references public.content_franchises(id), experiment_id uuid references public.experiments(id), hook_label text, duration_seconds integer, caption_summary text, views bigint, reach bigint, impressions bigint, likes bigint, comments bigint, shares bigint, saves bigint, profile_visits bigint, outbound_clicks bigint, follows_generated bigint, measured_at timestamptz, source text, data_confidence public.data_confidence not null default 'UNKNOWN', created_at timestamptz not null default now(), unique(social_account_id,external_post_id));
create table public.tracking_links (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), name text not null, channel text, campaign text, content_id uuid, source_url text, destination_url text not null, external_tracking_id text, active boolean not null default true, created_at timestamptz not null default now(), unique(creator_id,name));
create table public.landing_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), session_id text not null, source text, campaign text, device_type text, event_type text not null, path text, occurred_at timestamptz not null default now());
create table public.creator_revenue_daily (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), date date not null, platform text not null, creator_platform_receipts numeric, subscription_revenue numeric, additional_content_revenue numeric, tips_revenue numeric, other_revenue numeric, refunds numeric, chargebacks numeric, active_subscribers integer, new_subscribers integer, expired_subscribers integer, renewal_eligible integer, renewed integer, first_buyers integer, repeat_buyers integer, paying_fans integer, source text not null, data_confidence public.data_confidence not null default 'UNKNOWN', imported_at timestamptz not null default now(), unique(creator_id,date,platform,source));
create table public.daily_creator_reports (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), report_date date not null, generated_at timestamptz not null default now(), status text not null, health_status text, summary text not null, primary_bottleneck text, priority text, metrics_json jsonb not null default '{}'::jsonb, anomalies_json jsonb not null default '[]'::jsonb, recommendations_json jsonb not null default '[]'::jsonb, data_quality_json jsonb not null default '{}'::jsonb, provider text not null, model text, reviewed_by uuid, reviewed_at timestamptz, unique(creator_id,report_date));
create table public.tasks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid references public.creators(id), prospect_id uuid references public.prospects(id), workflow_run_id uuid, title text not null, description text, department text, priority text, status text not null default 'OPEN', owner_user_id uuid, requested_by uuid, source_type text, source_id uuid, due_at timestamptz, completed_at timestamptz, blocked_reason text, sop_reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.creator_deliverables (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), title text not null, category text, quantity integer, due_at timestamptz, status text not null default 'REQUESTED', requested_at timestamptz not null default now(), acknowledged_at timestamptz, delivered_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.creator_execution_scores (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), score_date date not null, responsiveness numeric, content_completion numeric, deadline_adherence numeric, instruction_adherence numeric, consistency numeric, total_score numeric, trend text, created_at timestamptz not null default now(), unique(creator_id,score_date));
create table public.creator_health_scores (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), score_date date not null, total_score integer not null check(total_score between 0 and 100), band text not null, components_json jsonb not null, weights_json jsonb not null, hard_override text, calculated_by text not null, created_at timestamptz not null default now(), unique(creator_id,score_date));
create table public.creator_relationship_checkins (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), date date not null, sentiment text, satisfaction_score integer, open_concerns text, commitments text, notes text, owner uuid, created_at timestamptz not null default now());
create table public.meetings (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid references public.creators(id), prospect_id uuid references public.prospects(id), meeting_type text, scheduled_at timestamptz, occurred_at timestamptz, attendees jsonb not null default '[]'::jsonb, notes text, summary text, decisions text[], action_items jsonb, transcript_reference text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.creator_pnl_periods (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), period_start date not null, period_end date not null, creator_platform_receipts numeric, commission_rate numeric, foundry_revenue numeric, fan_ops_labor numeric, creator_success_labor numeric, editing_cost numeric, growth_labor numeric, creator_specific_software numeric, promotion_cost numeric, paid_traffic_cost numeric, contractor_cost numeric, other_direct_cost numeric, contribution_profit numeric, contribution_margin numeric, status text not null, finalized_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(creator_id,period_start,period_end));
create table public.traffic_campaigns (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), name text not null, type text, platform text, spend numeric, start_date date, end_date date, tracking_link_id uuid references public.tracking_links(id), impressions bigint, clicks bigint, subscriptions integer, attributed_revenue_d1 numeric, attributed_revenue_d7 numeric, attributed_revenue_d30 numeric, cac numeric, roas numeric, data_confidence public.data_confidence not null default 'UNKNOWN', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.creator_collaborations (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), collaborator_name text not null, collaborator_creator_id uuid references public.creators(id), platform text, campaign_name text, cost numeric, tracking_link_id uuid references public.tracking_links(id), start_date date, end_date date, subscribers integer, attributed_revenue numeric, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.workflow_definitions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, version integer not null, description text, steps_json jsonb not null, active boolean not null default true, created_at timestamptz not null default now(), unique(organization_id,name,version));
create table public.workflow_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid references public.creators(id), definition_id uuid not null references public.workflow_definitions(id), run_number text not null default ('ONB-'||extract(year from now())::text||'-'||lpad(nextval('onboarding_number_seq')::text,6,'0')), status public.workflow_status not null, idempotency_key text not null, current_step text, initiated_by uuid, correlation_id uuid not null default gen_random_uuid(), blockers_json jsonb not null default '[]'::jsonb, started_at timestamptz not null default now(), completed_at timestamptz, cancelled_at timestamptz, unique(organization_id,idempotency_key), unique(organization_id,run_number));
alter table public.tasks add constraint tasks_workflow_run_fk foreign key (workflow_run_id) references public.workflow_runs(id);
create table public.workflow_steps (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), workflow_run_id uuid not null references public.workflow_runs(id), step_key text not null, ordinal integer not null, status public.workflow_step_status not null default 'PENDING', attempts integer not null default 0, max_attempts integer not null default 3, started_at timestamptz, completed_at timestamptz, next_retry_at timestamptz, error_code text, error_message text, provider text, external_id text, idempotency_key text not null, metadata_json jsonb not null default '{}'::jsonb, unique(workflow_run_id,step_key), unique(organization_id,idempotency_key));
create table public.provisioned_resources (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), workflow_run_id uuid references public.workflow_runs(id), provider text not null, resource_type text not null, external_id text not null, display_name text, environment text not null, idempotency_key text not null, metadata_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), archived_at timestamptz, unique(organization_id,idempotency_key));
create table public.integration_connections (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid references public.creators(id), provider text not null, category text, status public.integration_status not null default 'NOT_CONFIGURED', environment text not null default 'mock', external_account_id text, connected_by uuid, connected_at timestamptz, last_sync_at timestamptz, last_error text, health text, metadata_json jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.tool_definitions (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), name text not null, version integer not null default 1, description text, risk_level integer not null check(risk_level between 0 and 5), required_permission text not null, requires_human_approval boolean not null default false, enabled boolean not null default true, created_at timestamptz not null default now(), unique(organization_id,name,version));
create table public.notifications (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), user_id uuid, creator_id uuid references public.creators(id), type text not null, title text not null, body text, resource_type text, resource_id uuid, read_at timestamptz, created_at timestamptz not null default now());
create table public.incidents (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid references public.creators(id), incident_number text, type text not null, title text not null, description text, severity text not null, status text not null default 'OPEN', owner uuid, detected_at timestamptz not null default now(), resolved_at timestamptz, resolution text, root_cause text, followup_required boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.creator_compliance_checks (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), check_type text not null, status text not null default 'NOT_STARTED', evidence_reference text, reviewed_by uuid, reviewed_at timestamptz, expires_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(creator_id,check_type));
create table public.weekly_creator_reports (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), period_start date not null, period_end date not null, report_json jsonb not null, provider text not null, generated_at timestamptz not null default now(), reviewed_by uuid, reviewed_at timestamptz, unique(creator_id,period_start));
create table public.monthly_business_reviews (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), period_start date not null, period_end date not null, review_json jsonb not null, generated_at timestamptz not null default now(), finalized_at timestamptz, unique(creator_id,period_start));
create table public.creator_baselines (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), creator_id uuid not null references public.creators(id), period_start date not null, period_end date not null, baseline_type text not null, version integer not null default 1, metrics_json jsonb not null, frozen_at timestamptz not null, created_by uuid, created_at timestamptz not null default now(), unique(creator_id,baseline_type,version));
create table public.data_import_runs (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), provider text not null, creator_id uuid references public.creators(id), source text, status text not null, idempotency_key text not null, rows_received integer not null default 0, rows_inserted integer not null default 0, rows_updated integer not null default 0, rows_rejected integer not null default 0, errors_json jsonb not null default '[]'::jsonb, started_at timestamptz not null default now(), completed_at timestamptz, unique(organization_id,idempotency_key));
create table public.capacity_snapshots (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), user_id uuid not null, department text not null, capacity_hours numeric not null, allocated_hours numeric not null, utilization_percentage numeric generated always as (case when capacity_hours=0 then null else allocated_hours/capacity_hours*100 end) stored, period daterange not null, created_at timestamptz not null default now());
create table public.audit_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), actor_type text not null check(actor_type in ('user','system','workflow','integration','ai')), actor_user_id uuid, actor_service text, actor_ai_provider text, action text not null, resource_type text not null, resource_id uuid, before_json jsonb, after_json jsonb, metadata_json jsonb not null default '{}'::jsonb, correlation_id uuid not null, workflow_run_id uuid references public.workflow_runs(id), ip_address inet, created_at timestamptz not null default now());
create table public.domain_events (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), event_name text not null, aggregate_type text not null, aggregate_id uuid not null, payload_json jsonb not null, correlation_id uuid not null, occurred_at timestamptz not null default now());
create table public.event_outbox (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), domain_event_id uuid not null unique references public.domain_events(id), topic text not null, payload_json jsonb not null, attempts integer not null default 0, available_at timestamptz not null default now(), published_at timestamptz, last_error text, created_at timestamptz not null default now());

create index prospects_org_pipeline_idx on public.prospects(organization_id,pipeline_stage) where archived_at is null;
create index creators_org_status_idx on public.creators(organization_id,status) where archived_at is null;
create index tasks_org_status_due_idx on public.tasks(organization_id,status,due_at);
create index workflow_runs_org_status_idx on public.workflow_runs(organization_id,status,started_at desc);
create index audit_events_org_created_idx on public.audit_events(organization_id,created_at desc);
create index revenue_creator_date_idx on public.creator_revenue_daily(creator_id,date desc);
create index reports_org_date_idx on public.daily_creator_reports(organization_id,report_date desc);
create index outbox_unpublished_idx on public.event_outbox(available_at) where published_at is null;

create or replace function public.is_organization_member(target_org uuid) returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.organization_memberships m where m.organization_id=target_org and m.user_id=(select auth.uid()) and m.active)
$$;
revoke all on function public.is_organization_member(uuid) from public;
grant execute on function public.is_organization_member(uuid) to authenticated, service_role;

do $$ declare table_name text; begin
  foreach table_name in array array['organizations','organization_memberships','custom_roles','prospects','prospect_activities','creator_applications','creators','creator_brand_profiles','creator_truth_items','creator_boundaries','content_pillars','content_franchises','creator_competitors','creative_patterns','experiments','content_requests','content_assets','content_inventory_snapshots','social_accounts','social_posts','tracking_links','landing_events','creator_revenue_daily','daily_creator_reports','tasks','creator_deliverables','creator_execution_scores','creator_health_scores','creator_relationship_checkins','meetings','creator_pnl_periods','traffic_campaigns','creator_collaborations','workflow_definitions','workflow_runs','workflow_steps','provisioned_resources','integration_connections','tool_definitions','notifications','incidents','creator_compliance_checks','weekly_creator_reports','monthly_business_reviews','creator_baselines','data_import_runs','capacity_snapshots','audit_events','domain_events','event_outbox'] loop
    execute format('alter table public.%I enable row level security',table_name);
    if table_name='organizations' then execute 'create policy tenant_isolation on public.organizations for all to authenticated using (public.is_organization_member(id)) with check (public.is_organization_member(id))';
    else execute format('create policy tenant_isolation on public.%I for all to authenticated using (public.is_organization_member(organization_id)) with check (public.is_organization_member(organization_id))',table_name); end if;
  end loop;
end $$;
alter table public.users enable row level security;
create policy own_user_profile on public.users for select to authenticated using (id=(select auth.uid()));

-- Browser clients are read-only. All business mutations pass through server-side
-- permission checks and a server-held service role; RLS still tenant-scopes reads.
revoke all on all tables in schema public from anon, authenticated;
grant select on all tables in schema public to authenticated;

create or replace function public.prevent_audit_mutation() returns trigger language plpgsql set search_path='' as $$ begin raise exception 'audit_events are append-only'; end $$;
create trigger audit_events_append_only before update or delete on public.audit_events for each row execute function public.prevent_audit_mutation();

commit;
